### ISSUE TITLE
Update Schema

### ISSUE THREAD

**Issue by christinechengubc** [christinechengubc/WargamersApp#42]
Games:

- title, publisher, category, min_players, max_players, min_playtime, max_playtime, year_published, description, image, rating, users_rated, complexity, available_copies, total_copies, condition, expansion_of (foreign key), bgg_id, show_main_page

Events:

- title, start time, end time, date, location, description, always_show, lead_exec (foreign key), fb_event_page

Execs:

- name, position, contact

Admin:

- username, password

**Comment by christinechengubc** [comment]
@terbb @bryceamiranda does this look good to you? I'm going to update the database CREATE scripts with these changes once you guys approve.

**Comment by terbb** [comment]
Yeah it looks good to me. Go for it
