### ISSUE TITLE
Handle Vulnerable Dependency

### ISSUE THREAD

**Issue by christinechengubc** [christinechengubc/WargamersApp#43]
![image](https://user-images.githubusercontent.com/12410721/40281863-3bc7cb8e-5c1b-11e8-9b52-2c678f91a899.png)

![image](https://user-images.githubusercontent.com/12410721/40281869-53585be2-5c1b-11e8-93ef-7dbd5ed38900.png)

**Comment by terbb** [comment]
Updated to hoek 5.0.3.
